=== dontseyit/WorldTourArchive/RaceSchema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/dontseyit/world-tour-archive/main/RaceSchema.json",
    "title": "Race",
    "description": "UCI World Tour Cycling Race",
    "type": "object",
    "properties": {
        "name": {
            "description": "Known name of the race",
            "type": "string"
            },
        "country": {
            "description": "Country where race is held",
            "type": "string"
            },
        "category": {
            "description": "Category of race",
            "type": "string",
            "enum": ["one-day", "stage", "monument", "grand-tour"]
            },
        "when": {
            "description": "The approximate date that race usually takes place",
            "type": "string"
            },
        "first_edition": {
            "description": "The year the race was held for the first time",
            "type": "string",
            "pattern": "^(18|19|20)\\d{2}$"
            },
        "distance": {
            "description": "The approximate distance of race if it's a one-day race",
            "minimum": 0,
            "maximum": 300,
            "type": ["number", "null"],
            "default": null
            },
        "is_classic": {
            "description": "If race is a classic, include the name of the classics",
            "type": ["string", "null"],
            "default": null
        },
        "also_known_as": {
            "description": "Other names or nicknames for the race",
            "type": "array",
            "default": []
        },
        "pcs_url": {
            "description": "URL for race on ProCyclingStats",
            "type": "string",
            "format": "uri"
        },
        "insights": {
            "description": "Fun or important, insightful information that is not merely textbook knowledge",
            "type": ["string", "null"],
            "default": null
        }
    },
    "required": ["name", "country", "category", "when", "first_edition", "distance", "is_classic"],
    "additionalProperties": false
}

=== dontseyit/WorldTourArchive/races/TirrenoAdriatico.json
{
    "name": "Tirreno-Adriatico",
    "country": "Italy",
    "category": "stage",
    "when": "March, April",
    "first_edition": "1966",
    "distance": null,
    "is_classic": null,
    "also_known_as": ["The Race of the two Seas", "La corsa dei due mari"],
    "pcs_url": "https://www.procyclingstats.com/race/tirreno-adriatico",
    "insights": null
}

=== dontseyit/WorldTourArchive/races/TourDownUnder.json
{
    "name": "Tour Down Under",
    "country": "Australia",
    "category": "stage",
    "when": "January",
    "first_edition": "1999",
    "distance": null,
    "is_classic": null,
    "also_known_as": ["Santos Tour Down Under"],
    "pcs_url": "https://www.procyclingstats.com/race/tour-down-under"
}

=== dontseyit/WorldTourArchive/races/OmloopHetNieuwsblad.json
{
    "name": "Omloop Het Nieuwsblad",
    "country": "Belgium",
    "category": "one-day",
    "when": "Late February",
    "first_edition": "1945",
    "distance": 200,
    "is_classic": "Season openers",
    "also_known_as": ["The Omloop", "The Opening Classic"],
    "pcs_url": "https://www.procyclingstats.com/race/omloop-het-nieuwsblad",
    "insights": null
}

=== dontseyit/WorldTourArchive/races/ParisNice.json
{
    "name": "Parisâ€“Nice",
    "country": "France",
    "category": "stage",
    "when": "March",
    "first_edition": "1933",
    "distance": null,
    "is_classic": null,
    "also_known_as": ["The Race to the Sun", "La Course au Soleil"],
    "pcs_url": "https://www.procyclingstats.com/race/paris-nice",
    "insights": null
}

=== dontseyit/WorldTourArchive/races/CadelEvansOceanRace.json
{
    "name": "Cadel Evans Great Ocean Road Race",
    "country": "Australia",
    "category": "one-day",
    "when": "January",
    "first_edition": "2015",
    "distance": 180,
    "is_classic": null,
    "also_known_as": [],
    "pcs_url": "https://www.procyclingstats.com/race/great-ocean-race",
    "insights": "The first race was held in 2015, as the farewell race for Cadel Evansâ€”Australia's only Tour de France winner or Road World Champion."
}

=== dontseyit/WorldTourArchive/races/StradeBianche.json
{
    "name": "Strade Bianche",
    "country": "Italy",
    "category": "one-day",
    "when": "1st or 2nd Saturday of March",
    "first_edition": "2007",
    "distance": 180,
    "is_classic": "Italian spring classics",
    "also_known_as": [],
    "pcs_url": "https://www.procyclingstats.com/race/strade-bianche",
    "insights": "Thibaut Pinot described it as 'the sixth Monument' of Classic road cycling because of its iconic parcours, difficulty and prestige. The race starts and finishes (Piazza del Campo) on Siena."
}
